# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2142192b9738fa74b861f35a8c970164ce0ffeb5f9c17e37676349e3e35710d2a21cd6fd2da042483c8273f945703e969eb469d61fdeab15b2592e110dc07269

test:
  secret_key_base: 60fc72d4a0a9ff5e9130c3747585ef264de5387ee21b81764c46a67d7e163c5d5e34059de27eae7d517a9feaee30e4ee76be6bf5719c571e6dcb92e98e2d726b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
